main: com.github.dawsonvilamaa.beaconwaypoint.Main
name: BeaconWaypoints
version: 1.0
api-version: 1.16
author: Dawson Vilamaa
description: Allows players to set waypoints at beacons
commands:
  waypoint:
    aliases: wp
    description: Add or remove a waypoint
    usage: /waypoint <name> <public | private>
    permission: BeaconWaypoint.waypoint
    permission-message: You don't have permission to use that command